#!/usr/bin/env python3
"""Create LMDB dataset for enchant header OCR training.

Reads training data from backend/ocr/enchant_header_model/<version>/enchant_header_train_data/
(generated by scripts/ocr/enchant_header_model/generate_training_data.py)
and creates LMDB at backend/ocr/enchant_header_model/<version>/enchant_header_train_data_lmdb/.

Usage:
    python3 scripts/ocr/enchant_header_model/create_lmdb.py              # active version
    python3 scripts/ocr/enchant_header_model/create_lmdb.py --version v2 # explicit version
"""

import argparse
import os
import subprocess
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from scripts.ocr.lib.model_version import resolve_version, version_dir, PROJECT_ROOT
LMDB_SCRIPT = os.path.join(PROJECT_ROOT, 'skills', 'ocr-trainer', 'scripts', 'create_lmdb_dataset.py')

parser = argparse.ArgumentParser(description='Create enchant header LMDB')
parser.add_argument('--version', default=None, help='Version folder name (default: active symlink)')
args = parser.parse_args()

version = resolve_version('enchant_header', args.version)
ver_dir = version_dir('enchant_header', version)

DATA_DIR = os.path.join(ver_dir, 'enchant_header_train_data')
LMDB_DIR = os.path.join(ver_dir, 'enchant_header_train_data_lmdb')


def main():
    if not os.path.isdir(DATA_DIR):
        print(f"Error: Training data not found at {DATA_DIR}")
        print("Run: python3 scripts/ocr/enchant_header_model/generate_training_data.py")
        sys.exit(1)

    if not os.path.isfile(LMDB_SCRIPT):
        print(f"Error: LMDB script not found at {LMDB_SCRIPT}")
        sys.exit(1)

    print(f"Version: {version}")
    print(f"Input:  {DATA_DIR}")
    print(f"Output: {LMDB_DIR}")

    result = subprocess.run(
        [sys.executable, LMDB_SCRIPT, '--input', DATA_DIR, '--output', LMDB_DIR],
        cwd=PROJECT_ROOT,
    )
    if result.returncode != 0:
        print("Error: LMDB creation failed.")
        sys.exit(1)

    print("Done.")


if __name__ == '__main__':
    main()
