"""baseline

Revision ID: f5f1995269d9
Revises: 
Create Date: 2026-03-06 00:00:14.748939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f1995269d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_pct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_effects_id'), 'effects', ['id'], unique=False)
    op.create_table('enchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('header_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('restriction', sa.Text(), nullable=True),
    sa.Column('binding', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('guaranteed_success', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('activation', sa.Text(), nullable=True),
    sa.Column('credit', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('header_text'),
    sa.UniqueConstraint('name', 'rank', 'slot', name='_enchant_name_rank_slot_uc')
    )
    op.create_index(op.f('ix_enchants_id'), 'enchants', ['id'], unique=False)
    op.create_table('game_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_game_items_id'), 'game_items', ['id'], unique=False)
    op.create_table('ocr_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('line_index', sa.SmallInteger(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('section', sa.Text(), nullable=True),
    sa.Column('ocr_model', sa.Text(), nullable=True),
    sa.Column('fm_applied', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('charset_mismatch', sa.Text(), nullable=True),
    sa.Column('image_filename', sa.Text(), nullable=False),
    sa.Column('is_stitched', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('trained_version', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_corrections_id'), 'ocr_corrections', ['id'], unique=False)
    op.create_index(op.f('ix_ocr_corrections_session_id'), 'ocr_corrections', ['session_id'], unique=False)
    op.create_table('reforge_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_name')
    )
    op.create_index(op.f('ix_reforge_options_id'), 'reforge_options', ['id'], unique=False)
    op.create_table('enchant_effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enchant_id', sa.Integer(), nullable=False),
    sa.Column('effect_id', sa.Integer(), nullable=True),
    sa.Column('effect_order', sa.Integer(), nullable=False),
    sa.Column('condition_text', sa.Text(), nullable=True),
    sa.Column('min_value', sa.Numeric(), nullable=True),
    sa.Column('max_value', sa.Numeric(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['effect_id'], ['effects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['enchant_id'], ['enchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enchant_id', 'effect_order', name='_enchant_effect_order_uc')
    )
    op.create_index(op.f('ix_enchant_effects_id'), 'enchant_effects', ['id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('game_item_id', sa.Integer(), nullable=True),
    sa.Column('prefix_enchant_id', sa.Integer(), nullable=True),
    sa.Column('suffix_enchant_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.Text(), nullable=True),
    sa.Column('item_grade', sa.Text(), nullable=True),
    sa.Column('erg_grade', sa.Text(), nullable=True),
    sa.Column('erg_level', sa.Integer(), nullable=True),
    sa.Column('special_upgrade_type', sa.Text(), nullable=True),
    sa.Column('special_upgrade_level', sa.Integer(), nullable=True),
    sa.Column('damage', sa.Integer(), nullable=True),
    sa.Column('magic_damage', sa.Integer(), nullable=True),
    sa.Column('additional_damage', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('protection', sa.Integer(), nullable=True),
    sa.Column('magic_defense', sa.Integer(), nullable=True),
    sa.Column('magic_protection', sa.Integer(), nullable=True),
    sa.Column('durability', sa.Integer(), nullable=True),
    sa.Column('piercing_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['game_item_id'], ['game_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prefix_enchant_id'], ['enchants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suffix_enchant_id'], ['enchants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    op.create_table('listing_enchant_effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('enchant_effect_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['enchant_effect_id'], ['enchant_effects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_enchant_effects_id'), 'listing_enchant_effects', ['id'], unique=False)
    op.create_table('listing_reforge_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('reforge_option_id', sa.Integer(), nullable=True),
    sa.Column('option_name', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('max_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reforge_option_id'], ['reforge_options.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_reforge_options_id'), 'listing_reforge_options', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_reforge_options_id'), table_name='listing_reforge_options')
    op.drop_table('listing_reforge_options')
    op.drop_index(op.f('ix_listing_enchant_effects_id'), table_name='listing_enchant_effects')
    op.drop_table('listing_enchant_effects')
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_enchant_effects_id'), table_name='enchant_effects')
    op.drop_table('enchant_effects')
    op.drop_index(op.f('ix_reforge_options_id'), table_name='reforge_options')
    op.drop_table('reforge_options')
    op.drop_index(op.f('ix_ocr_corrections_session_id'), table_name='ocr_corrections')
    op.drop_index(op.f('ix_ocr_corrections_id'), table_name='ocr_corrections')
    op.drop_table('ocr_corrections')
    op.drop_index(op.f('ix_game_items_id'), table_name='game_items')
    op.drop_table('game_items')
    op.drop_index(op.f('ix_enchants_id'), table_name='enchants')
    op.drop_table('enchants')
    op.drop_index(op.f('ix_effects_id'), table_name='effects')
    op.drop_table('effects')
    # ### end Alembic commands ###
