#!/usr/bin/env python3
"""Create LMDB dataset for enchant header OCR training.

Reads training data from backend/ocr/enchant_header_train_data/
(generated by scripts/generate_enchant_header_training.py)
and creates LMDB at the path specified in the training config.

Usage:
    python3 scripts/create_enchant_header_lmdb.py
"""

import os
import subprocess
import sys

import yaml

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG_PATH = os.path.join(PROJECT_ROOT, 'configs', 'enchant_header_training_config.yaml')
LMDB_SCRIPT = os.path.join(PROJECT_ROOT, 'skills', 'ocr-trainer', 'scripts', 'create_lmdb_dataset.py')
DATA_DIR = os.path.join(PROJECT_ROOT, 'backend', 'ocr', 'enchant_header_train_data')

with open(CONFIG_PATH, 'r', encoding='utf-8') as f:
    cfg = yaml.safe_load(f)

LMDB_DIR = os.path.join(PROJECT_ROOT, cfg['paths']['train_data'])


def main():
    if not os.path.isdir(DATA_DIR):
        print(f"Error: Training data not found at {DATA_DIR}")
        print("Run: python3 scripts/generate_enchant_header_training.py")
        sys.exit(1)

    if not os.path.isfile(LMDB_SCRIPT):
        print(f"Error: LMDB script not found at {LMDB_SCRIPT}")
        sys.exit(1)

    print(f"Input:  {DATA_DIR}")
    print(f"Output: {LMDB_DIR}")

    result = subprocess.run(
        [sys.executable, LMDB_SCRIPT, '--input', DATA_DIR, '--output', LMDB_DIR],
        cwd=PROJECT_ROOT,
    )
    if result.returncode != 0:
        print("Error: LMDB creation failed.")
        sys.exit(1)

    print("Done.")


if __name__ == '__main__':
    main()
